{
 "title": "Taxi dashboard",
 "time": { "from": "2024-03-13T05:57:45.838Z", "to": "2024-03-30T00:00:00.000Z" },
 "panels": [
  {
   "title": "Quantile = 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", column_quantile AS \"value\" FROM taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of not stable predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT number_not_stable_prediction AS \"value\", \"timestamp\" AS \"time\" FROM taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", prediction_drift AS \"value\" FROM taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns AS \"value\", \"timestamp\" AS \"time\" FROM taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values AS \"value\", \"timestamp\" AS \"time\" FROM taxi_metrics LIMIT 50 "
    }
   ]
  }
 ]
}